In [1]:
import numpy as np

In [2]:
vector = np.arange(1, 11)
print("Вектор з першими 10-ма натуральними числами:\n", vector)

Вектор з першими 10-ма натуральними числами:
 [ 1  2  3  4  5  6  7  8  9 10]


In [3]:
matrix_3x3 = np.zeros((3, 3))
print("\nМатриця 3x3, заповнена нулями:\n", matrix_3x3)



Матриця 3x3, заповнена нулями:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
matrix_5x5 = np.random.randint(1, 11, (5, 5))
print("\nМатриця 5x5, заповнена випадковими цілими числами в діапазоні від 1 до 10:\n", matrix_5x5)


Матриця 5x5, заповнена випадковими цілими числами в діапазоні від 1 до 10:
 [[ 2  9  3  5  9]
 [ 9  2  7  3  4]
 [ 5  9  6  7  2]
 [ 8  8 10 10 10]
 [ 8  4  6  3 10]]


In [5]:
matrix_4x4 = np.random.rand(4, 4)
print("\nМатриця 4x4, заповнена випадковими дійсними числами в діапазоні від 0 до 1:\n", matrix_4x4)


Матриця 4x4, заповнена випадковими дійсними числами в діапазоні від 0 до 1:
 [[0.84983676 0.00929812 0.43795606 0.33794081]
 [0.02031858 0.31871931 0.34947812 0.10020875]
 [0.98374966 0.75957853 0.60579667 0.25555785]
 [0.51988437 0.82485947 0.03193535 0.26881507]]


In [6]:
vector1 = np.random.randint(1, 11, 5)
vector2 = np.random.randint(1, 11, 5)
print("\nВектор1:\n", vector1)
print("Вектор2:\n", vector2)
print("Поелементне додавання:\n", vector1 + vector2)
print("Поелементне віднімання:\n", vector1 - vector2)
print("Поелементне множення:\n", vector1 * vector2)


Вектор1:
 [ 2  7  5 10  7]
Вектор2:
 [ 4  7  4 10  4]
Поелементне додавання:
 [ 6 14  9 20 11]
Поелементне віднімання:
 [-2  0  1  0  3]
Поелементне множення:
 [  8  49  20 100  28]


In [7]:
vector3 = np.random.rand(7)
vector4 = np.random.rand(7)
print("\nВектор3:\n", vector3)
print("Вектор4:\n", vector4)
print("Скалярний добуток:\n", np.dot(vector3, vector4))


Вектор3:
 [0.21948451 0.19163323 0.15444113 0.19732418 0.70870867 0.78294817
 0.98885711]
Вектор4:
 [0.58716363 0.1463266  0.84393918 0.08021965 0.71194625 0.95043289
 0.90653868]
Скалярний добуток:
 2.448221955648235


In [8]:
matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 3))
print("\nМатриця1:\n", matrix1)
print("Матриця2:\n", matrix2)
print("Добуток матриць:\n", np.dot(matrix1, matrix2))


Матриця1:
 [[6 6]
 [2 2]]
Матриця2:
 [[ 8  9 10]
 [10 10  4]]
Добуток матриць:
 [[108 114  84]
 [ 36  38  28]]


In [9]:
matrix3 = np.random.randint(1, 11, (3, 3))
print("\nМатриця3:\n", matrix3)
print("Обернена матриця:\n", np.linalg.inv(matrix3))


Матриця3:
 [[ 9  1  2]
 [ 5  2  4]
 [10  4  5]]
Обернена матриця:
 [[ 0.15384615 -0.07692308  0.        ]
 [-0.38461538 -0.64102564  0.66666667]
 [ 0.          0.66666667 -0.33333333]]


In [10]:
matrix4 = np.random.rand(4, 4)
print("\nМатриця4:\n", matrix4)
print("Транспонована матриця:\n", matrix4.T)


Матриця4:
 [[0.30212966 0.96061745 0.89722666 0.48881466]
 [0.22338315 0.81893159 0.03697476 0.21867681]
 [0.14088762 0.03180556 0.07100018 0.83539864]
 [0.62430572 0.58223006 0.76941922 0.8116525 ]]
Транспонована матриця:
 [[0.30212966 0.22338315 0.14088762 0.62430572]
 [0.96061745 0.81893159 0.03180556 0.58223006]
 [0.89722666 0.03697476 0.07100018 0.76941922]
 [0.48881466 0.21867681 0.83539864 0.8116525 ]]


In [11]:
matrix5 = np.random.randint(1, 11, (3, 4))
vector5 = np.random.randint(1, 11, 4)
print("\nМатриця5:\n", matrix5)
print("Вектор5:\n", vector5)
print("Добуток матриці на вектор:\n", np.dot(matrix5, vector5))


Матриця5:
 [[10  5  9 10]
 [ 1  6  2 10]
 [ 8  9  4  5]]
Вектор5:
 [7 3 6 3]
Добуток матриці на вектор:
 [169  67 122]


In [12]:
matrix6 = np.random.rand(2, 3)
vector6 = np.random.rand(3)
print("\nМатриця6:\n", matrix6)
print("Вектор6:\n", vector6)
print("Добуток матриці на вектор:\n", np.dot(matrix6, vector6))


Матриця6:
 [[0.33917655 0.86465656 0.26739274]
 [0.5075764  0.60273042 0.56357246]]
Вектор6:
 [0.96701158 0.65972506 0.43028917]
Добуток матриці на вектор:
 [1.01347945 1.13096775]


In [13]:
matrix7 = np.random.randint(1, 11, (2, 2))
matrix8 = np.random.randint(1, 11, (2, 2))
print("\nМатриця7:\n", matrix7)
print("Матриця8:\n", matrix8)
print("Поелементне множення:\n", matrix7 * matrix8)


Матриця7:
 [[6 2]
 [8 9]]
Матриця8:
 [[8 4]
 [9 2]]
Поелементне множення:
 [[48  8]
 [72 18]]


In [14]:
matrix9 = np.random.randint(1, 11, (2, 2))
matrix10 = np.random.randint(1, 11, (2, 2))
print("\nМатриця9:\n", matrix9)
print("Матриця10:\n", matrix10)
print("Добуток матриць:\n", np.dot(matrix9, matrix10))


Матриця9:
 [[9 9]
 [7 1]]
Матриця10:
 [[ 8  7]
 [ 1 10]]
Добуток матриць:
 [[ 81 153]
 [ 57  59]]


In [15]:
matrix_5x5 = np.random.randint(1, 101, (5, 5))
print("Матриця 5x5:\n", matrix_5x5)
print("Сума елементів матриці:", np.sum(matrix_5x5))

Матриця 5x5:
 [[ 28   5  16  29  83]
 [100  97  81  76  19]
 [ 61  26  63  69  49]
 [ 34   2  43  95   1]
 [ 80   8  73  36   2]]
Сума елементів матриці: 1176


In [16]:
matrix1_4x4 = np.random.randint(1, 11, (4, 4))
matrix2_4x4 = np.random.randint(1, 11, (4, 4))
print("\nМатриця1 4x4:\n", matrix1_4x4)
print("Матриця2 4x4:\n", matrix2_4x4)
print("Різниця між матрицями:\n", matrix1_4x4 - matrix2_4x4)


Матриця1 4x4:
 [[ 9  1  4  2]
 [ 9  4  8  9]
 [10  6  3  3]
 [ 6  9  1  1]]
Матриця2 4x4:
 [[ 7  8  4  7]
 [ 5  7 10  8]
 [ 3  3 10  2]
 [ 7  1 10  1]]
Різниця між матрицями:
 [[ 2 -7  0 -5]
 [ 4 -3 -2  1]
 [ 7  3 -7  1]
 [-1  8 -9  0]]


In [17]:
matrix_3x3 = np.random.rand(3, 3)
print("\nМатриця 3x3:\n", matrix_3x3)
print("Вектор-стовпчик з сумою елементів кожного рядка:\n", np.sum(matrix_3x3, axis=1))


Матриця 3x3:
 [[0.28177207 0.06605684 0.6497468 ]
 [0.66004235 0.80244955 0.29711251]
 [0.34323207 0.3404239  0.24586849]]
Вектор-стовпчик з сумою елементів кожного рядка:
 [0.9975757  1.75960441 0.92952447]


In [18]:
matrix_3x4 = np.random.randint(1, 11, (3, 4))
print("\nМатриця 3x4:\n", matrix_3x4)
print("Матриця з квадратами чисел:\n", np.square(matrix_3x4))


Матриця 3x4:
 [[4 4 3 9]
 [3 8 6 5]
 [6 9 1 6]]
Матриця з квадратами чисел:
 [[16 16  9 81]
 [ 9 64 36 25]
 [36 81  1 36]]


In [19]:
vector_4 = np.random.randint(1, 51, 4)
print("\nВектор:\n", vector_4)
print("Вектор з квадратними коренями чисел:\n", np.sqrt(vector_4))


Вектор:
 [ 7 32  9 24]
Вектор з квадратними коренями чисел:
 [2.64575131 5.65685425 3.         4.89897949]


In [24]:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print("Заміна непарних чисел на -1:\n", arr)

Заміна непарних чисел на -1:
 [ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [27]:
arr_2d = np.arange(10).reshape(2, -1)
print("1D-масив, перетворений на 2D-масив із 2 рядками:\n", arr_2d)

1D-масив, перетворений на 2D-масив із 2 рядками:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [28]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
c = np.vstack((a, b))
print("Вертикальне об'єднання масивів a і b:\n", c)

Вертикальне об'єднання масивів a і b:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [29]:
a = np.array([1, 2, 3])
out = np.r_[np.repeat(a, 3), np.tile(a, 3)]
print("Шаблон без жорсткого кодування:\n", out)

Шаблон без жорсткого кодування:
 [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [30]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
common = np.intersect1d(a, b)
print("Спільні елементи між a і b:\n", common)

Спільні елементи між a і b:
 [2 4]


In [31]:
np.random.seed(100)
a = np.random.uniform(1, 50, 20)
max_positions = a.argsort()[-5:][::-1]
print("Позиції перших 5 максимальних значень у масиві a:\n", max_positions)

Позиції перших 5 максимальних значень у масиві a:
 [15 10  3  7 18]


In [32]:
a = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])
a = a[~np.isnan(a)]
print("Масив без значень NaN:\n", a)

Масив без значень NaN:
 [1. 2. 3. 5. 6. 7.]


In [33]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])
dist = np.linalg.norm(a-b)
print("Евклідова відстань між a і b:\n", dist)

Евклідова відстань між a і b:
 6.708203932499369


In [34]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5
idx = np.where(x == 1)[0][n-1]
print("Індекс 5-го повторення числа 1 у масиві x:\n", idx)

Індекс 5-го повторення числа 1 у масиві x:
 8


In [36]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
out = np.full(a.shape[0], True)
unique_positions = np.unique(a, return_index=True)[1]
out[unique_positions] = False
print("Повторювані записи у масиві a:\n", out)
print("Повторювані записи у масиві a:\n", a)

Повторювані записи у масиві a:
 [False  True False  True False False  True  True  True  True]
Повторювані записи у масиві a:
 [0 0 3 0 2 4 2 2 2 2]
